# Practice_Part_01 Data Structure's Solution


### Exercise_01 Solution

1. Create a Series objects using NumPy's linspace and random functions.

In [1]:
# Step_1: Import the pandas and numpy 

In [2]:
import pandas as pd 
import numpy as np

In [3]:
# Step_2: use linspace to create a Series with your own num (num: Number of samples to generate and default it is 50)
# You can easily check out the docstring of linspace on numpy method(I reccommend you to check the docstring before you work on it)
# np.linspace?

In [4]:
# With num=5
samples = np.linspace(1, 10, 5)
samples

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [5]:
# Pass the above sample to create a Series
series_1 = pd.Series(samples) 
series_1

0     1.00
1     3.25
2     5.50
3     7.75
4    10.00
dtype: float64

In [6]:
print(series_1)

0     1.00
1     3.25
2     5.50
3     7.75
4    10.00
dtype: float64


In [7]:
# Without num (Default it is set to 50)
sample_50 = np.linspace(1, 10)
sample_50[:10]

array([1.        , 1.18367347, 1.36734694, 1.55102041, 1.73469388,
       1.91836735, 2.10204082, 2.28571429, 2.46938776, 2.65306122])

In [8]:
# Pass the above 'sample_50' to create a Series
series_1 = pd.Series(sample_50) 
print(series_1.head()) 

0    1.000000
1    1.183673
2    1.367347
3    1.551020
4    1.734694
dtype: float64


In [9]:
# Step_3: use NumPy's random function to create a Series with some random values 

In [10]:
# np.random.rand?

In [11]:
random = np.random.rand(10)
random

array([0.19374125, 0.87775358, 0.80324314, 0.72284791, 0.5833805 ,
       0.68344788, 0.5886209 , 0.52526193, 0.91228087, 0.48999242])

In [12]:
ser_2 = pd.Series(random) 
print(ser_2) 

0    0.193741
1    0.877754
2    0.803243
3    0.722848
4    0.583381
5    0.683448
6    0.588621
7    0.525262
8    0.912281
9    0.489992
dtype: float64


### Exercise_02 Solution
1. Create a Series using a list of elements.

In [13]:
# Import the Pandas: Here I've already imported in the first Exercise So no need to import it again and again 

In [14]:
# Step_1: Create a list of elements of your choice 

In [15]:
list_elements = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [16]:
# Pass the above list to the Series constructor to create a Series

In [17]:
ser_3 = pd.Series(list_elements)
ser_3

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

### Exercise_03 Solution

1. For the data given below, get the index and values after forming a Series object.

In [18]:
# Import the pandas 

In [19]:
# Step_1: Create pandas Series using the data given

# Data = {"India": "New Delhi", "Japan": "Tokyo", "UK": "London"}

In [20]:
Data = {"India": "New Delhi", "Japan": "Tokyo", "UK": "London"}
ser_data = pd.Series(Data)
ser_data

India    New Delhi
Japan        Tokyo
UK          London
dtype: object

In [21]:
# Step_2: Now apply 'index' and 'values' attributes on the created Series object to get the index and values of a Series

In [22]:
ser_data.index

Index(['India', 'Japan', 'UK'], dtype='object')

In [23]:
ser_data.values

array(['New Delhi', 'Tokyo', 'London'], dtype=object)

### Exercise_04 Solution

1. Create a Series using a range of 10 values and specify the index explicitly. Use capital alphabets to index explicitly.

In [24]:
# Import Pandas and Numpy: Here I've already imported

In [25]:
# Step_1: Create a array of 10 values using NumPy's 'arange' function

In [26]:
values = np.arange(10)
values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# Step_2: Create a index list using capital alphabets starting with 'A'

In [28]:
index_values = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [29]:
# Step_3: Use these data sets 'values' and 'index_values' to create a Series 

In [30]:
ser_explicit_index = pd.Series(values, index=index_values)
ser_explicit_index

A    0
B    1
C    2
D    3
E    4
F    5
G    6
H    7
I    8
J    9
dtype: int32

### Exercise_05 Solution

1. For the Exercise_04, find the 'Shape' and 'Size' of the Series created

In [31]:
# Let's apply 'shape' and 'size' attributes for the Series created in Exercise_04

In [32]:
ser_explicit_index.shape

(10,)

In [33]:
ser_explicit_index.size

10

### Exercise_06 Solution

Slice the values of Series created for Exercise_04.
* (a). Slice from 4th index upto the end with step size 3
* (b). Slice the entire Series in reverse order
* (c). Slice the entire Series with step size 2

In [34]:
# Step_1:
# Let's Slice from 4 up to the end with step size 3 using '::' infront of the startig index here it is 4

In [35]:
ser_explicit_index[4::3]

E    4
H    7
dtype: int32

In [36]:
# Step_2:
# To slice the values in reverse order we can use '-1' after the step index notation '::'

In [37]:
ser_explicit_index[::-1]

J    9
I    8
H    7
G    6
F    5
E    4
D    3
C    2
B    1
A    0
dtype: int32

In [38]:
# Step_3
# Now finally slice the values starting from 0 upto the end with the step size 2 

In [39]:
ser_explicit_index[::2]

A    0
C    2
E    4
G    6
I    8
dtype: int32

### Exercise_07 Solution

1. Convert the Series object values created for Exercise_04 back into the list of values.

In [40]:
# Step_1:
# Check the type of the Object before conversion

In [41]:
print(type(ser_explicit_index))

<class 'pandas.core.series.Series'>


In [42]:
# Step_2:
# convert the Series Oject values into a respective list of elements using 'tolist' method on the Series

In [43]:
# You can easily check the docstring of 'tolist' on Pandas Series object(I recommend you to check the docstring)
# pd.Series.tolist?

In [44]:
print(ser_explicit_index.tolist())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [45]:
# Step_3:
# Chect the type of the object after conversion for confirmation

In [46]:
print(type(ser_explicit_index.tolist()))

<class 'list'>


### Exercise_08 Solution

1. For the data given below, Construct a Series and add data=[500, 600, 700] to the existing Series.

In [47]:
# Step_1: construct the Series using data given
# data = ['25', '50', '100', '200', '300', '400']
# data_to_add = [500, 600, 700] 

In [48]:
data = ['25', '50', '100', '200', '300', '400']

In [49]:
series_before = pd.Series(data)
series_before

0     25
1     50
2    100
3    200
4    300
5    400
dtype: object

In [50]:
# Step_2: Construct the another Series using 'data_to_add' 

In [51]:
data_to_add=['500', '600', '700']
series_toAppend = pd.Series(data_to_add)
series_toAppend

0    500
1    600
2    700
dtype: object

In [52]:
# Step_3: Now add this Series 'Series_toAppend' to the existing Series 'series_before' using 'append' method

In [53]:
series_after = series_before.append(series_toAppend)
series_after

C:\Users\Adel\AppData\Local\Temp\ipykernel_11940\2204600541.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  series_after = series_before.append(series_toAppend)


0     25
1     50
2    100
3    200
4    300
5    400
0    500
1    600
2    700
dtype: object

### Exercise_09 Solution

1. For the Series created in Exercise_08, get the subset of Series for the condition given below. condtion = 'values greater than or equal to 100"

In [54]:
# Step_1: Recall the Series

In [55]:
series_after

0     25
1     50
2    100
3    200
4    300
5    400
0    500
1    600
2    700
dtype: object

In [56]:
# Step_2: First convert the created Series with the string values to numeric using 'pd.to_numeric' method which 
# converts the given Series with string values to Series with numeric values. 

In [57]:
# You can easily check out the docstring of 'to_numeric' method on pandas object by yourself.
# pd.to_numeric?

In [58]:
new_series = pd.to_numeric(series_after)
new_series

0     25
1     50
2    100
3    200
4    300
5    400
0    500
1    600
2    700
dtype: int64

In [59]:
# Step_3: Apply the condition to the numeric Series created just now using indexing method inside the '[]'

In [60]:
new_sorted = new_series[new_series >= 100]
new_sorted

2    100
3    200
4    300
5    400
0    500
1    600
2    700
dtype: int64

### Exercise_10 Solution

1. For the data given below constuct a Pandas DataFrame object. Use labels data to set the index of the DataFrame. After creating the DataFrame display the summary of the basic information.

In [61]:
# Step_1: Create a DataFrame object using the data provided.
"""
exam_data  = {'name': ['Arun', 'Rama', 'Kantharaj', 'James', 'Emily', 'Michael', 
                       'Matthew', 'Laura', 'Kevin', 'Jonas'], 
              'score': [12, 10, 17, np.nan, 9, 30, 15, np.nan, 8, 19], 
              'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 
              'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} 
              
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] 
"""

"\nexam_data  = {'name': ['Arun', 'Rama', 'Kantharaj', 'James', 'Emily', 'Michael', \n                       'Matthew', 'Laura', 'Kevin', 'Jonas'], \n              'score': [12, 10, 17, np.nan, 9, 30, 15, np.nan, 8, 19], \n              'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], \n              'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} \n              \nlabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] \n"

In [62]:
exam_data  = {'name': ['Arun', 'Rama', 'Kantharaj', 'James', 'Emily', 'Michael', 
                       'Matthew', 'Laura', 'Kevin', 'Jonas'], 
              'score': [12, 10, 17, np.nan, 9, 30, 15, np.nan, 8, 19], 
              'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 
              'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} 
              
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] 

In [63]:
exam_df = pd.DataFrame(exam_data , index=labels)
exam_df

name  score  attempts qualify
a       Arun   12.0         1     yes
b       Rama   10.0         3      no
c  Kantharaj   17.0         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   30.0         3     yes
g    Matthew   15.0         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [64]:
# Step_2: Display the basic information of the DataFrame using 'info' method 

In [65]:
exam_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10 non-null     object 
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64  
 3   qualify   10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


### Exercise_11 Solution
1. Find the names of the people who has scored greater than 12 in Exercise_10
2. Separate the people with score and without any score for the Exercise_10

In [66]:
# Step_1: Use the loc method to select the names who scores > 12

In [67]:
exam_df.loc[exam_df['score'] > 12]

name  score  attempts qualify
c  Kantharaj   17.0         2     yes
f    Michael   30.0         3     yes
g    Matthew   15.0         1     yes
j      Jonas   19.0         1     yes

In [68]:
# Step_2: Use the 'notnull' and 'isnull' methods to separate the names with and without any score

In [69]:
exam_df[exam_df['score'].notnull()]

name  score  attempts qualify
a       Arun   12.0         1     yes
b       Rama   10.0         3      no
c  Kantharaj   17.0         2     yes
e      Emily    9.0         2      no
f    Michael   30.0         3     yes
g    Matthew   15.0         1     yes
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [70]:
exam_df[exam_df['score'].isnull()]

name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

### Exercise_12 Solution
1. Find the participants who qualify the test and who didn't qualify the test in Exercise_10

In [71]:
# Step_1: Use the indexing method with loc to select the names who qualify the test. Use '==' symbol to select with the particular condition

In [72]:
exam_df

name  score  attempts qualify
a       Arun   12.0         1     yes
b       Rama   10.0         3      no
c  Kantharaj   17.0         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   30.0         3     yes
g    Matthew   15.0         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [73]:
exam_df.loc[exam_df['qualify'] == 'yes']

name  score  attempts qualify
a       Arun   12.0         1     yes
c  Kantharaj   17.0         2     yes
f    Michael   30.0         3     yes
g    Matthew   15.0         1     yes
j      Jonas   19.0         1     yes

In [74]:
# Step_2: Now after using the 'yes' string use 'no' string in the condition to select who didn't qualify the test

In [75]:
exam_df.loc[exam_df['qualify'] == 'no']

name  score  attempts qualify
b   Rama   10.0         3      no
d  James    NaN         3      no
e  Emily    9.0         2      no
h  Laura    NaN         1      no
i  Kevin    8.0         2      no

### Exercise_13 Solution
1. For the Exercise_10, separete the columns without score and form a separate DataFrame. 

In [76]:
# Step_1:Filter the dataframe by selecting multiple columns without score column.
# Pass a list of column names to the indexing method within the [].

In [77]:
new_df = exam_df[['name', 'attempts', 'qualify']]
new_df

name  attempts qualify
a       Arun         1     yes
b       Rama         3      no
c  Kantharaj         2     yes
d      James         3      no
e      Emily         2      no
f    Michael         3     yes
g    Matthew         1     yes
h      Laura         1      no
i      Kevin         2      no
j      Jonas         1     yes

### Exercise_14 Solution
1. For the Exercise_10, find the number of participants with first attempt.

In [78]:
# Step_1: Select the 'attempts' column 

In [79]:
attempt_first = exam_df['attempts']
attempt_first

a    1
b    3
c    2
d    3
e    2
f    3
g    1
h    1
i    2
j    1
Name: attempts, dtype: int64

In [80]:
# Step_2: use value_counts to method to count the number of participants who did first attempt 

In [81]:
attempt_first.value_counts()

1    4
3    3
2    3
Name: attempts, dtype: int64

In [82]:
# We got 4 participants who did first attempt 

In [83]:
# Alternatvely we can also use fancy indexing with loc and len method to to count the number of participants who did first attempt 

In [84]:
len(exam_df.loc[exam_df['attempts'] == 1])

4

### Exercise_15
1.  For the Exercise_10 separate the column score and find the top score 

In [85]:
# Step_1: separate the column using indexing method

In [86]:
score = exam_df['score']
score

a    12.0
b    10.0
c    17.0
d     NaN
e     9.0
f    30.0
g    15.0
h     NaN
i     8.0
j    19.0
Name: score, dtype: float64

In [87]:
# Step_2 use the max() function to find the top score on the separated column

In [88]:
score.max()

30.0